name: Deploy
run-name: ${{ gitea.actor }} is deploying ${{ gitea.repository }}
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.157.0'
          extended: true

      - name: Install dart-sass
        uses: dw-labs-org/dart-sass-gha@v1

      - name: Build site
        run: hugo build --gc --minify --baseURL ${{ vars.BASE_URL }}
