name: Deploy
run-name: ${{ gitea.actor }} is deploying ${{ gitea.repository }}
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: hugo
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Build site
        run: hugo build --gc --minify --baseURL ${{ vars.BASE_URL }} --destination ${{ vars.DESTINATION }}
