name: Deploy
run-name: ${{ gitea.actor }} is deploying ${{ gitea.repository }}
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: host
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.165.0'
          extended: true

      - name: Build site
        # XXX removed --minify until https://github.com/gohugoio/hugo/issues/15257 is addressed
        run: |
          hugo build --gc --baseURL https://post-self.ink --destination /opt/hugo/post-self.ink
